version: "3"
services:
    api:
        environment:
            - DOCKER=true
            - CHOKIDAR_USEPOLLING=true
        build:
            context: .
            dockerfile: docker/api
        depends_on:
            - mongo
        networks:
            main:
                aliases:
                    - core_api
        ports:
            - 80:80
        volumes:
            - ./server:/usr/src/core/server
            - /usr/src/core/server/node_modules
    ui:
        environment:
            - CHOKIDAR_USEPOLLING=true
        build:
            context: .
            dockerfile: docker/front-end
        depends_on:
            - api
        networks:
            main:
                aliases:
                    - core_ui
        ports:
            - 8080:8080
        volumes:
            - ./client:/usr/src/core/client
            - /usr/src/core/client/node_modules
    mongo:
        image: mongo
        networks:
            main:
                aliases:
                    - mongo
        ports:
            - 27017:27017
networks:
    main:
